/*  Common elements for code generated by Gene-Auto  */

#ifndef __GACommon__
#define __GACommon__

/* Function-like macros */

#define falling(newIn, oldIn) ((oldIn) > 0 && (newIn) <= 0 || (oldIn) == 0 && (newIn) < 0)

#define u_falling(newIn, oldIn) ((oldIn) > 0 && (newIn) == 0)

#define rising(newIn, oldIn) ((oldIn) < 0 && (newIn) >= 0 || (oldIn) == 0 && (newIn) > 0)

#define u_rising(newIn, oldIn) ((oldIn) == 0 && (newIn) > 0)


#endif
