/*
    simple_olg.c
    Generated by Gene-Auto toolset ver 2.4.10
    (launcher GALauncher)
    Generated on: 25/04/2014 10:26:30.965
    source model: simple_olg
    model version: 7.2
    last saved by:
    last saved on:
*/

/* Includes */

#include "base.h"
#include "simple_olg.h"

/* Variable definitions */

REAL simple_olg_yd = 0.0;
REAL simple_olg_y = 0.0;

/* Function definitions */

/*@ 
        requires \valid(_state_);
*/
void simple_olg_init(t_simple_olg_state *_state_) {
    _state_->Integrator_1_memory = 1;
    _state_->Integrator_2_memory = 1;
}

/*@ 
        logic matrix QMat_0 = mat_of_1x1_scalar(1.0);
*/
/*@ 
        logic matrix QMat_1 = mat_of_2x2_scalar(1710.0449662492558,-41.101885746811455,-41.101885746811455,499.17657993449376);
*/
/*@ 
        logic matrix QMat_2 = mat_mult(mat_mult(mat_of_3x2_scalar(1.0,0.0,0.0,1.0,1.0,0.0),QMat_1),transpose(mat_of_3x2_scalar(1.0,0.0,0.0,1.0,1.0,0.0)));
*/
/*@ 
        logic matrix QMat_3 = mat_mult(mat_mult(mat_of_1x1_scalar(1.0),QMat_0),transpose(mat_of_1x1_scalar(1.0)));
*/
/*@ 
        logic matrix QMat_4 = mat_mult(mat_mult(mat_of_4x3_scalar(1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,564.48),QMat_2),transpose(mat_of_4x3_scalar(1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,564.48)));
*/
/*@ 
        logic matrix QMat_5 = mat_mult(mat_mult(mat_of_1x1_scalar(1.0),QMat_3),transpose(mat_of_1x1_scalar(1.0)));
*/
/*@ 
        logic matrix QMat_6 = mat_mult(mat_mult(mat_of_5x4_scalar(1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.01,0.0),QMat_4),transpose(mat_of_5x4_scalar(1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.01,0.0)));
*/
/*@ 
        logic matrix QMat_7 = mat_mult(mat_mult(mat_of_1x1_scalar(1.0),QMat_5),transpose(mat_of_1x1_scalar(1.0)));
*/
/*@ 
        logic matrix QMat_8 = mat_mult(mat_mult(mat_of_6x5_scalar(1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0),QMat_6),transpose(mat_of_6x5_scalar(1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0)));
*/
/*@ 
        logic matrix QMat_9 = mat_mult(mat_mult(mat_of_1x1_scalar(1.0),QMat_7),transpose(mat_of_1x1_scalar(1.0)));
*/
/*@ 
        logic matrix QMat_10 = mat_mult(mat_mult(mat_of_7x6_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0),QMat_8),transpose(mat_of_7x6_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0)));
*/
/*@ 
        logic matrix QMat_11 = mat_mult(mat_mult(mat_of_1x1_scalar(1.0),QMat_9),transpose(mat_of_1x1_scalar(1.0)));
*/
/*@ 
        logic matrix QMat_12 = QMat_11;
*/
/*@ 
        logic matrix QMat_13 = mat_mult(mat_mult(mat_of_6x7_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0),QMat_10),transpose(mat_of_6x7_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0)));
*/
/*@ 
        logic matrix QMat_14 = QMat_12;
*/
/*@ 
        logic matrix QMat_15 = mat_mult(mat_mult(mat_of_6x6_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0),QMat_13),transpose(mat_of_6x6_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0)));
*/
/*@ 
        logic matrix QMat_16 = QMat_14;
*/
/*@ 
        logic matrix QMat_17 = mat_mult(mat_mult(mat_of_6x6_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0),QMat_15),transpose(mat_of_6x6_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0)));
*/
/*@ 
        logic matrix QMat_18 = mat_mult(mat_mult(mat_of_2x1_scalar(1.0,-1280.0),QMat_16),transpose(mat_of_2x1_scalar(1.0,-1280.0)));
*/
/*@ 
        logic matrix QMat_19 = mat_mult(mat_mult(mat_of_6x6_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0),QMat_17),transpose(mat_of_6x6_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0)));
*/
/*@ 
        logic matrix QMat_20 = block_m(mat_scalar_mult(1.0009008207386647,QMat_19),zeros(6,2),zeros(2,6),mat_scalar_mult(1111.111122222222,QMat_18));
*/
/*@ 
        logic matrix QMat_21 = mat_mult(mat_mult(mat_of_9x8_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0),QMat_20),transpose(mat_of_9x8_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0)));
*/
/*@ 
        logic matrix QMat_22 = mat_mult(mat_mult(mat_of_8x9_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0),QMat_21),transpose(mat_of_8x9_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0)));
*/
/*@ 
        logic matrix QMat_23 = mat_mult(mat_mult(mat_of_7x8_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,50.1,0.0,0.0,0.0,0.0,0.0),QMat_22),transpose(mat_of_7x8_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,50.1,0.0,0.0,0.0,0.0,0.0)));
*/
/*@ 
        logic matrix QMat_24 = mat_mult(mat_mult(mat_of_8x7_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0),QMat_23),transpose(mat_of_8x7_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0)));
*/
/*@ 
        logic matrix QMat_25 = mat_mult(mat_mult(mat_of_8x8_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0),QMat_24),transpose(mat_of_8x8_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,-1.0)));
*/
/*@ 
        logic matrix QMat_26 = mat_mult(mat_mult(mat_of_7x8_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.01),QMat_25),transpose(mat_of_7x8_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.01)));
*/
/*@ 
        logic matrix QMat_27 = mat_mult(mat_mult(mat_of_7x7_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0),QMat_26),transpose(mat_of_7x7_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0)));
*/
/*@ 
        logic matrix QMat_28 = mat_mult(mat_mult(mat_of_6x7_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0),QMat_27),transpose(mat_of_6x7_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0)));
*/
/*@ 
        logic matrix QMat_29 = mat_mult(mat_mult(mat_of_4x6_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0),QMat_28),transpose(mat_of_4x6_scalar(1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0)));
*/
/*@ 
        logic matrix QMat_30 = mat_mult(mat_mult(mat_of_2x4_scalar(0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0),QMat_29),transpose(mat_of_2x4_scalar(0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0)));
*/
/*@ 
        requires \valid(_io_) && \valid(_state_);
        requires in_ellipsoidQ(QMat_0,vect_of_1_scalar(_io_->y - _io_->yd));
        requires in_ellipsoidQ(QMat_1,vect_of_2_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory));
        requires \separated(_io_,_state_);
        ensures in_ellipsoidQ(QMat_1,vect_of_2_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory));
        ensures \separated(_io_,_state_);
*/
void simple_olg_compute(t_simple_olg_io *_io_, t_simple_olg_state *_state_) {
    REAL A11;
    REAL A12;
    REAL A21_dt;
    REAL C11;
    REAL D11;
    REAL Integrator_1;
    REAL Integrator_2;
    REAL Sum1;
    REAL Sum2;
    REAL Sum3;
    REAL Sum4;
    REAL Sum5;
    REAL control_output;
    REAL dt_;
    REAL x_t_[2];
    REAL yd_t_[1];
    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior EllipsoidInput_0:
            requires in_ellipsoidQ(QMat_0,vect_of_1_scalar(_io_->y - _io_->yd));
            ensures in_ellipsoidQ(QMat_3,vect_of_1_scalar(_io_->y - _io_->yd));
            @ PROOF_TACTIC (use_strategy (Identity));
            
            behavior ElllipsoidMain_0:
            requires in_ellipsoidQ(QMat_1,vect_of_2_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory));
            ensures in_ellipsoidQ(QMat_2,vect_of_3_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
    */
 {
    Integrator_1 = _state_->Integrator_1_memory;
 }

    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior EllipsoidInput_1:
            requires in_ellipsoidQ(QMat_3,vect_of_1_scalar(_io_->y - _io_->yd));
            ensures in_ellipsoidQ(QMat_5,vect_of_1_scalar(_io_->y - _io_->yd));
            @ PROOF_TACTIC (use_strategy (Identity));
            
            behavior ElllipsoidMain_1:
            requires in_ellipsoidQ(QMat_2,vect_of_3_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1));
            ensures in_ellipsoidQ(QMat_4,vect_of_4_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
    */
 {
    C11 = 564.48 * Integrator_1;
 }

    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior EllipsoidInput_2:
            requires in_ellipsoidQ(QMat_5,vect_of_1_scalar(_io_->y - _io_->yd));
            ensures in_ellipsoidQ(QMat_7,vect_of_1_scalar(_io_->y - _io_->yd));
            @ PROOF_TACTIC (use_strategy (Identity));
            
            behavior ElllipsoidMain_2:
            requires in_ellipsoidQ(QMat_4,vect_of_4_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11));
            ensures in_ellipsoidQ(QMat_6,vect_of_5_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11,A21_dt));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
    */
 {
    A21_dt = 0.01 * Integrator_1;
 }

    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior EllipsoidInput_3:
            requires in_ellipsoidQ(QMat_7,vect_of_1_scalar(_io_->y - _io_->yd));
            ensures in_ellipsoidQ(QMat_9,vect_of_1_scalar(_io_->y - _io_->yd));
            @ PROOF_TACTIC (use_strategy (Identity));
            
            behavior ElllipsoidMain_3:
            requires in_ellipsoidQ(QMat_6,vect_of_5_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11,A21_dt));
            ensures in_ellipsoidQ(QMat_8,vect_of_6_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11,A21_dt,Integrator_2));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
    */
 {
    Integrator_2 = _state_->Integrator_2_memory;
 }

    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior EllipsoidInput_4:
            requires in_ellipsoidQ(QMat_9,vect_of_1_scalar(_io_->y - _io_->yd));
            ensures in_ellipsoidQ(QMat_11,vect_of_1_scalar(_io_->y - _io_->yd));
            @ PROOF_TACTIC (use_strategy (Identity));
            
            behavior ElllipsoidMain_4:
            requires in_ellipsoidQ(QMat_8,vect_of_6_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11,A21_dt,Integrator_2));
            ensures in_ellipsoidQ(QMat_10,vect_of_7_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11,A21_dt,Integrator_2,Sum3));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
    */
 {
    Sum3 = A21_dt + Integrator_2;
 }

    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior EllipsoidInput_5:
            requires in_ellipsoidQ(QMat_11,vect_of_1_scalar(_io_->y - _io_->yd));
            ensures in_ellipsoidQ(QMat_12,vect_of_1_scalar(simple_olg_y - _io_->yd));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
            
            behavior ElllipsoidMain_5:
            requires in_ellipsoidQ(QMat_10,vect_of_7_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11,A21_dt,Integrator_2,Sum3));
            ensures in_ellipsoidQ(QMat_13,vect_of_6_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11,Integrator_2,Sum3));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
    */
 {
    simple_olg_y = _io_->y;
 }

    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior EllipsoidInput_6:
            requires in_ellipsoidQ(QMat_12,vect_of_1_scalar(simple_olg_y - _io_->yd));
            ensures in_ellipsoidQ(QMat_14,vect_of_1_scalar(simple_olg_y - simple_olg_yd));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
            
            behavior ElllipsoidMain_6:
            requires in_ellipsoidQ(QMat_13,vect_of_6_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11,Integrator_2,Sum3));
            ensures in_ellipsoidQ(QMat_15,vect_of_6_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11,Integrator_2,Sum3));
            @ PROOF_TACTIC (use_strategy (Identity));
    */
 {
    simple_olg_yd = _io_->yd;
 }

    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior EllipsoidInput_7:
            requires in_ellipsoidQ(QMat_14,vect_of_1_scalar(simple_olg_y - simple_olg_yd));
            ensures in_ellipsoidQ(QMat_16,vect_of_1_scalar(Sum4));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
            
            behavior ElllipsoidMain_7:
            requires in_ellipsoidQ(QMat_15,vect_of_6_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11,Integrator_2,Sum3));
            ensures in_ellipsoidQ(QMat_17,vect_of_6_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11,Integrator_2,Sum3));
            @ PROOF_TACTIC (use_strategy (Identity));
    */
 {
    Sum4 = simple_olg_y - simple_olg_yd;
 }

    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior EllipsoidInput_8:
            requires in_ellipsoidQ(QMat_16,vect_of_1_scalar(Sum4));
            ensures in_ellipsoidQ(QMat_18,vect_of_2_scalar(Sum4,D11));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
            
            behavior ElllipsoidMain_8:
            requires in_ellipsoidQ(QMat_17,vect_of_6_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11,Integrator_2,Sum3));
            ensures in_ellipsoidQ(QMat_19,vect_of_6_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11,Integrator_2,Sum3));
            @ PROOF_TACTIC (use_strategy (Identity));
    */
 {
    D11 = -1280.0 * Sum4;
 }

    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior ElllipsoidMain_9:
            requires in_ellipsoidQ(QMat_18,vect_of_2_scalar(Sum4,D11));
            requires in_ellipsoidQ(QMat_19,vect_of_6_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11,Integrator_2,Sum3));
            ensures in_ellipsoidQ(QMat_20,vect_of_8_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11,Integrator_2,Sum3,Sum4,D11));
            @ PROOF_TACTIC (use_strategy (SProcedure));
    */
 {

 }
    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior ElllipsoidMain_10:
            requires in_ellipsoidQ(QMat_20,vect_of_8_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11,Integrator_2,Sum3,Sum4,D11));
            ensures in_ellipsoidQ(QMat_21,vect_of_9_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11,Integrator_2,Sum3,Sum4,D11,control_output));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
    */
 {
    control_output = D11 + C11;
 }

    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior ElllipsoidMain_11:
            requires in_ellipsoidQ(QMat_21,vect_of_9_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,C11,Integrator_2,Sum3,Sum4,D11,control_output));
            ensures in_ellipsoidQ(QMat_22,vect_of_8_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,Integrator_2,Sum3,Sum4,control_output,_io_->u));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
    */
 {
    _io_->u = control_output;
 }

    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior ElllipsoidMain_12:
            requires in_ellipsoidQ(QMat_22,vect_of_8_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,Integrator_2,Sum3,Sum4,control_output,_io_->u));
            ensures in_ellipsoidQ(QMat_23,vect_of_7_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,Integrator_2,Sum3,Sum4,A11));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
    */
 {
    A11 = 50.1 * Integrator_1;
 }

    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior ElllipsoidMain_13:
            requires in_ellipsoidQ(QMat_23,vect_of_7_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,Integrator_2,Sum3,Sum4,A11));
            ensures in_ellipsoidQ(QMat_24,vect_of_8_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,Integrator_2,Sum3,Sum4,A11,A12));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
    */
 {
    A12 = 5.0 * Integrator_2;
 }

    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior ElllipsoidMain_14:
            requires in_ellipsoidQ(QMat_24,vect_of_8_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,Integrator_2,Sum3,Sum4,A11,A12));
            ensures in_ellipsoidQ(QMat_25,vect_of_8_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,Sum3,Sum4,A11,A12,Sum1));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
    */
 {
    Sum1 = -A12 - A11;
 }

    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior ElllipsoidMain_15:
            requires in_ellipsoidQ(QMat_25,vect_of_8_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,Sum3,Sum4,A11,A12,Sum1));
            ensures in_ellipsoidQ(QMat_26,vect_of_7_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,Sum3,Sum4,Sum1,dt_));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
    */
 {
    dt_ = 0.01 * Sum1;
 }

    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior ElllipsoidMain_16:
            requires in_ellipsoidQ(QMat_26,vect_of_7_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,Sum3,Sum4,Sum1,dt_));
            ensures in_ellipsoidQ(QMat_27,vect_of_7_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,Sum3,Sum4,dt_,Sum2));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
    */
 {
    Sum2 = dt_ + Integrator_1;
 }

    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior ElllipsoidMain_17:
            requires in_ellipsoidQ(QMat_27,vect_of_7_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Integrator_1,Sum3,Sum4,dt_,Sum2));
            ensures in_ellipsoidQ(QMat_28,vect_of_6_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Sum3,Sum4,Sum2,Sum5));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
    */
 {
    Sum5 = Sum4 + Sum2;
 }

    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior ElllipsoidMain_18:
            requires in_ellipsoidQ(QMat_28,vect_of_6_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Sum3,Sum4,Sum2,Sum5));
            ensures in_ellipsoidQ(QMat_29,vect_of_4_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Sum3,Sum5));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
    */
 {
    _state_->Integrator_2_memory = Sum3;
 }

    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior ElllipsoidMain_19:
            requires in_ellipsoidQ(QMat_29,vect_of_4_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory,Sum3,Sum5));
            ensures in_ellipsoidQ(QMat_30,vect_of_2_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory));
            @ PROOF_TACTIC (use_strategy (AffineEllipsoid));
    */
 {
    _state_->Integrator_1_memory = Sum5;
 }

    /*@ 
            requires \separated(_io_,_state_);
            ensures \separated(_io_,_state_);
            
            behavior ElllipsoidMain_20:
            requires in_ellipsoidQ(QMat_30,vect_of_2_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory));
            ensures in_ellipsoidQ(QMat_1,vect_of_2_scalar(_state_->Integrator_1_memory,_state_->Integrator_2_memory));
            @ PROOF_TACTIC (use_strategy (PosDef));
    */
 {

 }
}

